<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
if ($category) {
    $subcats = $category->getChildrenCategories();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    ?>
    <ul style="padding: 0px;float: left;width: 100%">
        <?php
        foreach ($subcats as $subcat) {
            if ($subcat->getIsActive()) {
                $_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
                $_outputhelper = $this->helper('Magento\Catalog\Helper\Output');
                $subcaturl = $subcat->getUrl();
 
                $_imgHtml = '';
                if ($_imgUrl = $_category->getImageUrl()) {
 
                    $_imgHtml = '<img style="width: 100%;" src="' . $_imgUrl . '" />';
                    $_imgHtml = $_outputhelper->categoryAttribute($_category, $_imgHtml, 'image');
 
                    /* @escapeNotVerified */
                    echo '<li style="list-style-type: none;width:24%;margin-right:1%;float:left"><a href="' . $subcaturl . '
                " class="block-promo" title="' . $subcat->getName() . '">' . $_imgHtml . '
                </a></li>';
                }
            }
        } ?>
    </ul>
<?php } ?>